kubernetes-incubator/rktlet

CONTRIBUTING.md, README.md, code-of-conduct.md
This provides some basic information.
cc @yifan-gu @tmrts
=> Initial readme

docs/initial-design.md
The proposal in #3 was for discussion.
This attempts to distil that discussion into specific decisions and supersedes that PR.
This PR is fairly light on details, and I'd be happy to include more details or entertain more discussion on some parts, though the main motivation is to get the ball rolling.
cc @kubernetes-incubator/maintainers-rktlet @vishh
=> docs: Initial design document

rktlet/cli/init.go, rktlet/runtime/exec.go, rktlet/runtime/pod_sandbox.go
Use `rkt app exec --app=$appname $UUID CMD ARGS...` to implement Exec().
=> CRI: Implement Exec().

docs/getting-started-guide.md
Need to get some examples of the pods / apps' statuses.
=> docs: Add getting started guide.

rktlet/cli/init.go, rktlet/cli/interfaces.go, rktlet/cli/mocks/init.go, rktlet/runtime/helpers.go, rktlet/runtime/pod_sandbox.go
=> CRI: Add `--slice=${cgroup_parent}` to support cgroup parent.

.travis.yml, Makefile, rktlet/image/imagestore_test.go, rktlet/runtime/pod_sandbox.go, rktlet/runtime/rkt_runtime.go
=> Add initial travis-ci configuration

rktlet/image/imagestore.go, rktlet/image/imagestore_test.go
=> Image: Add filter for image.

rktlet/runtime/pod_sandbox.go
The kubelet behaves badly when RunPodSandbox doesn't return a running sandbox
=> sandbox: Make sure it's running before returning

rktlet/runtime/helpers.go
TODO: needs tests. I'm planning to make sure there aren't quoting/security edge-cases for paths in those tests.
I manually tested that it worked for a trivial hostpath mount.
=> runtime: Add app bindmounts

cmd/server/main.go
This makes it more consistent with how external consumers are expected
to use it.
Split out from #54 since this'll be handy to have separately.
=> cmd: refactor to use rktlet pkg

cmd/server/main.go, cmd/server/options/options.go, docs/getting-started-guide.md, glide.lock, glide.yaml, rktlet/rktlet.go, vendor/github.com/golang/glog/README, vendor/github.com/golang/glog/glog.go
Depends on #46 
Yes it's really basic. I mostly want something like this for the integ tests I'm writing so I can make sure everything ends up in a temporary directory, and we can make it more complicated and powerful when we need to.
=> Add some basic config options

rktlet/rktlet.go, rktlet/runtime/helpers.go, rktlet/runtime/rkt_runtime.go
=> Allow local fetched images

rktlet/runtime/helpers.go
This was an easy todo. I removed another comment that I think is
outdated as well
=> runtime: add --dns-opt

rktlet/runtime/helpers.go, rktlet/runtime/log.go, rktlet/runtime/pod_sandbox.go, rktlet/runtime/rkt_runtime.go
Part of #52 
Rebased on top of #68 since it uses a helper function introduced in that commit.
=> Run logging helper

rktlet/runtime/pod_sandbox.go
Temporary workaround for an upstream issue..
=> runtime: retry 'rm's a few times

rktlet/runtime/rkt_runtime.go
This also allows filtering by podsandbox id to work as expected
=> runtime: populate sandboxID for container correctly

rktlet/image/imagestore.go
=> image: reduce log noise, if original annotation is not present in image

README.md, docs/getting-started-guide.md
=> README: add links & fix typo

rktlet/image/imagestore.go, rktlet/runtime/helpers.go, rktlet/runtime/stage1.go
The rkt CLI changed so we need to update calls accordingly.
=> rkt CLI changes

rktlet/runtime/helpers.go, rktlet/runtime/pod_sandbox.go
=> runtime: fix panics

rktlet/runtime/helpers.go
It's actually a struct containing an int64 field.
=> runtime: fix RunAsUser

rktlet/runtime/helpers.go
Let's check annotations to decide which `--seccomp=` option to pass to
the containers.
For now we only support
* unconfined: no seccomp. This is the default
* docker/default: which matches rkt's default
If we don't understand the annotation, we disable seccomp to improve
compatibility.
=> runtime: propagate seccomp options

rktlet/runtime/helpers.go
rkt doesn't create nonexistent volume directories while docker does.
Let's create them in the rktlet so we have the same behavior.
=> runtime: create host volume directories if they don't exist

rktlet/runtime/pod_sandbox.go
There was a race between `StopPodSandbox()` between `PodSandboxStatus()`, Even when `StopPodSandbox()` successfully stopped the PodSandbox, `PodSandboxStatus()` could still return the state READY. It should be actually NOTREADY. That's so especially when a client calls `PodSandboxStatus()` too fast.
So just like done in `RunPodSanbox()`, `StopPodSandbox()` should also wait for a while, up to 10 seconds, until the correct state was set. For that, let's create a common helper `waitPodSandboxStatus()` which can be called by both Run and Stop.
Fixes https://github.com/kubernetes-incubator/rktlet/issues/141
=> rktlet/runtime: wait until the PodSandbox's state became NOTREADY

rktlet/runtime/pod_sandbox.go
rkt v1.22.0 introduced the flags `--wait` and `--wait-ready` to wait for
a pod to terminate or to be ready respectively. Let's use those instead
of implementing wait loops in rktlet.
=> runtime: rework status gathering

docs/running-e2e-tests.md
=> docs: document how to run e2e tests

ROADMAP.md
=> ROADMAP: initial roadmap

RELEASE.md
The code is not meant to be vendored in the Kubelet anymore.
Also, fix some typos.
=> RELEASE.md: update release instructions

CHANGELOG.md, version/version.go
=> release v0.1.0

RELEASE.md
This describes the release process in a detailed way.
Fixes #174
=> RELEASE: update guide

docs/debugging.md
=> docs: add debugging guide

docs/features.md
=> docs: add feature matrix
