OWNERS, README.md, RELEASE.md
Per title, based on https://github.com/kubernetes/kubernetes-template-project
Once this is merged we should send a more formal announcement through sig-node and sig-rktnetes to raise awareness and hopefully find people interested in participating and helping!
=> Add Sponsor+Champion and more boilerplate

rktlet/cli/init.go, rktlet/runtime/exec.go, rktlet/runtime/helpers.go, rktlet/runtime/pod_sandbox.go, rktlet/runtime/rkt_runtime.go
Depend on several PRs:
https://github.com/kubernetes-incubator/rktlet/pull/24 (which depends on https://github.com/coreos/rkt/pull/3205)
https://github.com/coreos/rkt/pull/3225 (which adds `--format=json` to `rkt status`, and add `annotations`, `started_at` field in the json).
=> Add pod level annotations, app level annotations.

rktlet/runtime/helpers.go, rktlet/runtime/helpers_test.go
cc @euank 
Would modify the upstream to remove unnecessary `Name` field, and the skip when `host port == 0`.
=> CRI: Support exposing ports.

rktlet/rktlet.go
I think it makes sense to have this interface for e.g. kubernetes to directly use.
It also makes sense to tie runtime + image together closely since, well, they are inter-dependent (shared data directory).
=> Add higher level package for easier consumption

cmd/server/options/options.go, rktlet/cli/cli.go, rktlet/cli/cli_test.go, rktlet/cli/init.go, rktlet/image/imagestore.go, rktlet/rktlet.go
Prior to this change, it emitted no flags due to a flipped `IsValid`
check.
This fixes the fact that the configured data directory was totally ignored.
=> cli: fix flag reflection

docs/getting-started-guide.md
In #48, default data directory was meant to be changed, but due to a bug (fixed in #61), that didn't take effect. Docs should have probably been edited in #48, but never too late to follow up :)
=> docs: add a section about the datadir default

rktlet/runtime/helpers.go
This was missed and is needed by a lot of important cluster components.
cc @squeed.
=> rktlet: host network support

journal2cri/.gitignore, journal2cri/Dockerfile, journal2cri/Dockerfile.build, journal2cri/Makefile
This includes an option to build it in docker (required for release so
your crazy gentoo CFLAGS don't spit out a broken binary).
This is just another piecemeal step in merging in the logging changes that worked off in my branch.
=> journal2cri: add release target

rktlet/runtime/pod_sandbox.go, rktlet/runtime/pod_sandbox_test.go
The included test failed prior to the small pod_sandbox change.
This is due to the usual gotcha of loop variables in go sharing the same
address, and the `toPodSandboxStatus` function returns references to
parts of that struct, which end up becoming wrong after another loop.
I'm pretty sure this explains a lot of troubles I've had with kubelet not being able to find some pod UIDs.
=> runtime: fix list pod sandbox reference-overriding

rktlet/cli/errors.go, rktlet/runtime/pod_sandbox.go
This makes us more closely follow CRI api expectations
=> runtime: make stop idempotent, stop before rm

rktlet/runtime/helpers.go
`ImageStatus` can return `{}, nil`, and #52 missed this case.
=> runtime: correctly error on nonexistent image

Makefile, tests/README.md, tests/framework/framework.go, tests/runtime/runtime_test.go
These don't get run by CI yet.
I'd like to do that as a followup.
These also do not pass in general until #61 is merged.
=> tests: add basic integ test framework

rktlet/runtime/helpers.go
I've got an integ test for this too, but it's blocked on privileged so it can read `/sys/fs/cgroup`, and as such I haven't actually run the test.
I'd prefer to followup with it once privileged is there.
=> runtime: support cpushares correctly

rktlet/runtime/helpers.go, tests/runtime/runtime_test.go
This fixes an oversight in #80. The sandbox needs all privileges in order to grant them to individual processes, and the test wasn't good enough to catch that since the sandbox always had sys_admin regardless
cc @s-urbaniak
=> runtime: privileged => all-run for the sandbox

.gitignore, Makefile, tests/framework/framework.go, tests/runtime/runtime_test.go
This sets up a local GOPATH under `.gopath`, used for building and testing.
It also speeds up integration tests by using a single tempdir for all runs.
=> tests: setup a local GOPATH

cmd/server/options/options.go, rktlet/rktlet.go, rktlet/runtime/helpers.go, rktlet/runtime/log.go, rktlet/runtime/pod_sandbox.go, rktlet/runtime/rkt_runtime.go, rktlet/runtime/stage1.go, tests/framework/framework.go, tests/runtime/runtime_test.go
The current rkt integration makes it possible to configure the stage1
image so we should do the same in the rktlet.
=> rktlet: make stage1-name configurable

rktlet/runtime/exec.go, tests/runtime/runtime_test.go
A bug in Exec() prevented error status codes from being passed
back to CRI, misrouting them instead as rktlet errors.
=> runtime/exec: do not mix errors and status codes

journal2cri/journal2cri/journal2cri.go
This ignores journald entries not originating from pod applications,
i.e. "systemd-journald" itself.
Fixes #98
=> journal2cri: ignore non-k8s entries

rktlet/runtime/helpers.go
Since host networking implies host UTS [[1]] and rkt doesn't support
sharing the host's UTS namespace, let's at least set the hostname to the
host's.
[1]: https://github.com/kubernetes/kubernetes/blob/088c198224c00f8402448b0cfff5b6689ea892fa/pkg/kubelet/dockershim/security_context.go#L185
=> runtime: set hostname to host's if --net=host

rktlet/cli/init.go
Otherwise, an error in the run command is not detected and `systemd-run`
returns 0 in any case. (`systemd-run false ; echo $?` versus
`systemd-run --service=notify false ; echo $?`)
With this change, an error in a transient unit (as described in
https://github.com/kubernetes-incubator/rktlet/issues/108) would be
easier to debug, as `RunPodSandbox` now returns the actual error to the
kubelet.
=> rktlet/cli/init: set `--service-type=notify`

rktlet/runtime/log.go
If no LogDir is given to `RunPodSandbox()`, we should make rktlet run with `/var/log/pods/rkt_uuid` by default. Otherwise tools like cri-tools would fail like that:
```
remote_runtime.go:92] RunPodSandbox from runtime service failed:
rpc error: code = Unknown desc = unable to start logging:
no cri log directory provided
```
=> rktlet: make criLogDir default to /var/log/pods/rkt_uuid

cmd/server/options/options.go, rktlet/rktlet.go, rktlet/runtime/helpers.go, rktlet/runtime/pod_sandbox.go, rktlet/runtime/rkt_runtime.go
According to the CRI Networking Specification[[1]], the runtime shim is
responsible of managing pod's network life cycle. However, the current
CRI API doesn't expose options like `network-plugin`, `cni-bin-dir`, or
`cni-conf-dir`.
This adds a new `--net` option to the rktlet so users can specify what
network they want to use for pods. We rely on rkt to set up the network
so these are the paths where rkt looks for CNI configurations and
binaries:
* Network configurations: `/etc/rkt/net.d`
* Plugin binaries: `/usr/lib/rkt/plugins/net`
Note that rkt also includes some plugins[[2]] in the default stage1.
[1]: https://github.com/kubernetes/community/blob/c1eab08/contributors/devel/kubelet-cri-networking.md
[2]: https://github.com/rkt/rkt/blob/v1.28.1/Documentation/networking/overview.md#built-i …
=> rktlet: add network plugin name flag

rktlet/image/imagestore.go
`runtime.RemoveImageResponse.Image` can be nil, so we need to check for that Image being nil again.
Otherwise it panics like this:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x88d3a4]
goroutine 79 [running]:
.../rktlet/image.(*ImageStore).RemoveImage(0xc4200ab640, 0x7f4074eee1d0,
0xc420085050, 0xc42012e1d0, 0xc197a0, 0xc4201cb101, 0xc42012e1d0)
.../.gopath/src/github.com/kubernetes-incubator/rktlet/rktlet/image/imagestore.go:68 +0xe4
```
=> rktlet/image: fix nil dereference in RemoveImage()

docs/getting-started-guide.md, rktlet/cli/init.go, rktlet/cli/init_test.go
When the kubelet is started with --cgroups-per-qos, it will request pods
to be created in a specific cgroup. Since rktlet starts rkt as a systemd
unit, it needs to specify a systemd slice name that represent the
requested cgroup.
Unfortunately, not all cgroup paths are representable as systemd slice
names. The Kubelet must be started with --cgroup-driver=systemd
(CGROUP_DRIVER=systemd in hack/local-up-cluster.sh), otherwise the
cgroupParent will not be convertible.
Fixes https://github.com/kubernetes-incubator/rktlet/issues/44
-----------------
TODO:
=> Convert cgroup-parent to a systemd slice name

rktlet/cli/errors.go
When `rkt stop` returns error because of UUID mismatch, the output Error string is not simply like `"cannot get pod: no matches found for ..."`, but actually like below:
```
failed to run stop [--force=false 3c0ec67e-c02a-41b5-b053-e1b5d6e2fe06]: exit status 254 output: stop: cannot get pod: no matches found for "3c0ec67e-c02a-41b5-b053-e1b5d6e2fe06" stop: failed to stop 1 pod(s)
```
(in one string)
That's why regexp matching doesn't work. The substring `cannot get pod...` is neither located in the beginning of the input string, nor at the end of the string. As a result, `rkt stop` always fails in case of UUID mismatch, as `RktStopIsNotExistError()` always returns false. That's why critools tests fail like:
```
E0927 16:45:09.004685    7605 remote_runtime.go:115] StopPodSandbox …
```
=> rktlet/cli: fix regexp to check for error string

docs/limitations.md, rktlet/runtime/helpers.go, rktlet/runtime/helpers_test.go, rktlet/runtime/rkt_runtime.go
As appc spec does not allow lowercase characters in ACName, we should sanitize ACName before running `rkt app`, for subcommands `add`, `exec`, `rm`, `start`, `status`, and `stop`. Otherwise each command will fail when app name contains an uppercase character like:
```
error adding app to pod: ACName must contain only lower case
alphanumeric characters plus "-"
```
Fixes https://github.com/kubernetes-incubator/rktlet/issues/134
=> rktlet/runtime: sanitize ACName before for running rkt app

rktlet/runtime/pod_sandbox.go
Issue https://github.com/rkt/rkt/issues/3423 is fixed so we don't need
to wait 3 seconds arbitrarily.
=> runtime: don't wait 3 seconds arbitrarily

rktlet/runtime/helpers.go
Otherwise, if `rkt app add` or `rkt app start` fails, we won't get any
logs in the journal and we'll be blind to the causes of the failure.
With this, users can at least run on the host:
and see why the app failed to start.
As a complete solution, we should somehow capture this journal output
and propagate it to the error returned in StartContainer().
=> runtime: start sandboxes with --debug

rktlet/image/imagestore.go, rktlet/runtime/rkt_runtime.go, rktlet/util/image.go, rktlet/util/image_test.go
If `rkt add app` runs with an image name without a prefix `docker://`, add a prefix `docker://`. If the image name doesn't contain `:`, try to change it to a canonical name like "busybox:latest".
This is especially needed for testing with cri tools.
Partly covers https://github.com/kubernetes-incubator/rktlet/issues/131
=> rktlet/runtime: make use of canonical image name

rktlet/image/imagestore.go, rktlet/util/image.go
In `ImageStatus()`, we need to take care of not only a human-readable string to be found in RepoTags, but also a pure hash string like  `"sha512-..."`. Otherwise critools tests will fail like below:
```                                                                                            
E0927 13:16:48.789812   13017 remote_image.go:130]                                             
RemoveImage "sha512-90e41be10f11188676633f562cd98822686928b80cda76bd8529a753f9b5d890"          
from image service failed: rpc error: code = Unknown desc = Image does not exist               
Sep 27 13:16:48.789: INFO: Unexpected error occurred: rpc error:                               
code = Unknown desc = Image does not exist                                                     
```
Fixes …
=> rktlet/image: take care of image name written as hash string

rktlet/image/imagestore.go, rktlet/runtime/pod_sandbox.go, rktlet/runtime/rkt_runtime.go
We should not ignore output from `RunCommand()`, since rkt commands could return important messages via stderr upon errors. Let's return them together with error strings.
This change might be helpful especially when doing investigation on failures from the remote k8s clusters, where no special logs are available.
=> image, runtime: do not ignore output from RunCommand

Makefile, cmd/server/main.go, cmd/server/options/options.go, hack/bump-release, version/version.go
It's set at build-time to the output of `git describe --dirty --always`.
At the moment it just prints a git commit hash because there is no
annotated tag. When we add the first tag, it should start working as
intended and print versions in the format `0.1.0`,
`0.1.0-${COMMITS_SINCE_LAST_TAG}-${COMMIT_HASH}`, or
`0.1.0-${COMMITS_SINCE_LAST_TAG}-${COMMIT_HASH}-dirty`.
=> cmd: add --version flag

Makefile
* Update builder image to golang 1.9.
* Include the ldflag to pass the version of rktlet to go's build system.
=> Makefile: update build-in-rkt

rktlet/cli/cli.go
To improve the logging, I added the output of the command in the `RunCommand`.
Before:
```text
W0210 16:29:10.157355     957 cli.go:151] rkt: cmd image [fetch --pull-policy=update --full=true docker://enjoliver.local/hyperkube:1.9.2] errored with exit status 254
```
After:
```text
W0210 17:01:27.783092    3748 cli.go:152] rkt: cmd image [fetch --pull-policy=update --full=true docker://enjoliver.local/hyperkube:1.9.2] errored with exit status 254, "fetch: Get https://enjoliver.local/v2/: dial tcp 172.20.0.1:443: getsockopt: connection refused\n"
```
=> cli: improve the logging when failed to run a command
